## Fundamentals of tensor using TensorFlow

### Content : 
- Intro to tensors
- Getting info from tensors
- manipulating tensors 
- Tensors and numpy
- Using @tf.function (a way to speed up your regular python functions)
- Using GPU andd TPU with TensorFlow
- Exerices to try

In [ ]:
# intro to tensors

# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Creating tensors with tf.constant()
#  Creates a constant tensor from a tensor-like object.
scalar =  tf.constant(7)
scalar

# o/p   :  1.shape of tensor : Shape as in normal shape(tow,col) of matrix or array
#       :  2.datatype of tensor 
#       :  3. numpy version of tensor and dtype of numpy version

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#  "ndim"  - no. of dimension of a tensor  
scalar.ndim
# 0 rank tensor 

0

In [ ]:
# create a vector 
vector = tf.constant((10,10))
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim
# 1 rank tensor 

1

In [ ]:
# create a matrix
# matrix has more than one dimension 
matrix = tf.constant((
    [10,7],
    [7,10]
))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim
# 2 rank tensor 

2

In [ ]:
# Creating another matrix
matrix2 = tf.constant(([1.2,1.3,1.4],
                       [2.,2.2,3.]))
print(matrix2.ndim)
matrix2

2


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.2, 1.3, 1.4],
       [2. , 2.2, 3. ]], dtype=float32)>

In [ ]:
# Same as above . only specifed the data-type
# Creating another matrix
data  =  [[1.2,1.3,1.4],[2.,2.2,3.]]
matrix2 = tf.constant(data,dtype='float16')   #   or tf.float16  
# or  tf.constant(data,dtype=tf.float16)
print('Dimension ',matrix2.ndim)
matrix2


Dimension  2


<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1.2, 1.3, 1.4],
       [2. , 2.2, 3. ]], dtype=float16)>

In [ ]:
# Creating a tensor 
tensor = tf.constant(
                   [
                      [[1,2,3],
                      [4,5,6]],
                     
                     [[1.,2.,3.],
                      [4.,5.,6.]]
                  ]
)
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)>

In [ ]:
tensor.ndim

3

### What we have learned so far :   
- Scalar  : Single Number            : 0D tensor
- Vector  : A Number with Direction  : 1D tensor  eg : wind , speed , velocity 
- matrix  : 2D array of numbers      : 2S tensor 
- Tensor  : An N-dimensional array of numbers where "n" can be any number

### Creating tensors with tf.Variable()
- Advantage of this func is that after creating a tensor we can modify that tensor

In [ ]:
#Now Creating tensors not with tf.constant()
# Using tf.variable()
# Creating same tensor as above using this method

tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor   = tf.Variable([10,20])

unchangeable_tenaor =  tf.constant([10,20])

In [ ]:
changeable_tensor , unchangeable_tenaor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>)

In [ ]:
changeable_tensor[0]  , unchangeable_tenaor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [ ]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 20], dtype=int32)>

In [ ]:
# assign_add --> it just add with prev values
changeable_tensor.assign_add([100,200])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([107, 220], dtype=int32)>

In [ ]:
# assign_sub --> it just sub with prev values
changeable_tensor.assign_sub([100,200])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 20], dtype=int32)>

In [ ]:
v = tf.Variable(1.)
v.assign(2.)

v.assign_add(0.5)


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.5>

In [ ]:
unchangeable_tenaor[0].assign(7)
# deliberately keeped the o/p of error since cant alter tensor created by constant

AttributeError: ignored

🔑  NOTE :    
- When we want to modify tensor after creating then  use `tf.Variable`
- If after wards in code we dont want to update tensor then use  `tf.constant`

###  Random Tensors  
- They are the tensors with arbitarty size and random numbers in it !

### Two  methods :    
1. normal   :  Outputs random values from a normal distribution(bell shape curve)
2. uniform   : Outputs random values from a uniform distribution.

In [ ]:
# Creating Random tensor 
random_tensor  =   tf.random.Generator.from_seed(40)
random_tensor

In [ ]:
# using normal  
random_tensor  =   random_tensor.normal(shape=(1,2))
random_tensor

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.0560527, 1.9540939]], dtype=float32)>

In [ ]:
# Creating Random tensor using uniform 

random_tensor_uniform  =   tf.random.Generator.from_seed(40)
random_tensor_uniform  = random_tensor_uniform.uniform(shape=(1,2)) 
random_tensor_uniform

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.6332247 , 0.15466881]], dtype=float32)>

In [ ]:
# More eay way 
tf.random.Generator.from_seed(30).normal(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545,  1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ,  0.00511209, -1.0493753 ],
       [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.23645182],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265]],
      dtype=float32)>

In [ ]:
random_tensor1  =   tf.random.Generator.from_seed(40)
random_tensor1  =   random_tensor1.normal(shape=(5,5))
random_tensor1

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345, -0.48535708,  0.74055266,  0.31662667],
       [-1.4391748 ,  0.58923835, -1.4268045 , -0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 , -0.23193763, -1.8107855 ,  0.09988727],
       [-0.50998646, -0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ]],
      dtype=float32)>

In [ ]:
random_tensor2  =   tf.random.Generator.from_seed(40)
random_tensor2  =   random_tensor2.normal(shape=(5,5))

In [ ]:
random_tensor2  == random_tensor1
# Both same becz od from_seed same value

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

### Shuffle the order of the  elements in a tensor :    
WHY shuffleing a tensor  ?<br> 
Ans :    
Useful when we want to shuffle our data  so that inherent order doesn't effect model learning<br> 
Eg :    
- In dataset if we have 1k one entry for wadapav and  next 5k  for samosa pav 
- then model will train 1st on first 1k then 5k 
- instead this we can shuffle the dataset 

In [ ]:
tensor_to_shuffle = tf.constant([[1,2,3],
                                 [4,5,6],
                                 [7,8,9]])
tensor_to_shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor_to_shuffle)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor_to_shuffle)
# Every time we will get ramdom o/p by shuffling the tensor data

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# so to shuffle many times and get same result we have to set the seed using set_seed()
tf.random.set_seed(42)
tensor_to_shuffle ,   tf.random.shuffle(tensor_to_shuffle)

# using set_seed every time we will get same shuffle o/p 

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]], dtype=int32)>)

### Exercise :     
- Q1 :    create a tensor with variable and shuffle 
- Q2 :    Create a tensor with constant and shuffle and use set_seed
- Q3 :    Shuffle random tensor 

In [ ]:
# Ans of exercise

# Q1  ans 
tf.random.shuffle( tf.constant([[[1,2,3],[4,5,6]],
                                [[7,8,9],[10,11,12]]]) )



<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [ ]:
# Q2 ans 
tf.random.set_seed(14)
tf.random.shuffle( tf.Variable([[[1,2,3],[4,5,6]],
                                [[7,8,9],[10,11,12]]]) )

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [ ]:
# Q3 ans 
tf.random.shuffle( tf.random.Generator.from_seed(15).normal(shape=(6,6)) )

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[-1.322665  , -0.02279496, -0.1383193 ,  0.44207528, -0.7531523 ,
         2.0261486 ],
       [ 0.33149973, -0.5445254 ,  1.5222508 ,  0.59303206, -0.63509274,
         0.3703566 ],
       [ 1.0884082 , -1.3863064 ,  0.88051325, -1.6833194 ,  0.86754173,
        -0.19625713],
       [ 0.35877243, -1.9095894 , -0.2094769 ,  0.8286217 , -0.06695071,
        -0.35105535],
       [-0.06997604,  0.85445154,  0.1175475 ,  0.03493892, -1.5700307 ,
         0.4457582 ],
       [-1.0939722 , -0.4601445 ,  1.5420506 , -0.16822556, -0.4390865 ,
        -0.4129243 ]], dtype=float32)>

Study diff b/w global seed : set_seed() & local seed : seed as parameter

- INSIGHT :         
> If both the global ad local seed are used together then ; both are used in conjuction to determine the random sequence.

**CONCLUSION** 
> we had used this seed for : creaing reproducable suffled o/p of tensor

### Other Ways to make tensors 
1. Numpy  (tf.constant(array,shape)

In [ ]:
# Creating array of all ones
tf.ones(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating array of all zeros using numpy 
tf.zeros(shape=(4,7))

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#### now converting arrays into tensors
- Main Difference betwee Tensor and Numpy Array is 
 >  Tensors runs on GPU with very Fast computation 

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10]) 
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array1 = np.arange(0,20)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# converting array to ttensor 

tf.constant(array)

<tf.Tensor: shape=(19,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])>

In [ ]:
tf.constant(array1 , shape=(5,4))
# note 5*4 = 20 (size of array1 is 20)

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [ ]:
tf.constant(array1 , shape=(5,2,2))
# note 5*2*2 = 20 (size of array1 is 20)

<tf.Tensor: shape=(5, 2, 2), dtype=int64, numpy=
array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])>

###  Getting More Information from tensors 

- Shape  : total elements in each dimension
> tensor.shape
- Rank :   No. of tensor dimension 
<br> Eg: scalar rank=0,vector rank=1,matrix rank =2 and tensor rank 3
> tensor.ndim
- Axis or Dimension  :  A perticular dimension of a tensor 
> tensor[0] , tensor[:,1]
- Size : The total no. of iteams in the tensor 
>tf.size()

In [ ]:
# Creating rank 4 tensor 
rank_4_tensor   = tf.constant(tf.zeros(shape=(2,3,4,5)))
rank_4_tensor

# Note : 
# shape:  2,3,4,5
# total 6 with divided in 2 we get 3 : hence  2,3
# 4 rows and 5 cols  : hence 4,5

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# 1st dimension from 0-1
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# 2nd dimension from 0-2 
rank_4_tensor[0][2]


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# 3rd dimension from 0-3  since 4rows
rank_4_tensor[0][2][3]


<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
# 4th dimension from 0-4  since 5cols
rank_4_tensor[0][2][3][4]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
print(' Get Various attributes For rank_4_tensor')
print()
print('Rank : ',rank_4_tensor.ndim,'\nShape : ',rank_4_tensor.shape,'\nSize(Total elem in tensor ) : ',tf.size(rank_4_tensor))
print('SIZE using.numpy()  : ',tf.size(rank_4_tensor).numpy())
print("Datatype of Every Element : ",rank_4_tensor.dtype)
print('Element along the 0 axis :',rank_4_tensor.shape[0])
print('Element along the Last axis :',rank_4_tensor.shape[-1])

# 2*3*4*5 = 120

 Get Various attributes For rank_4_tensor

Rank :  4 
Shape :  (2, 3, 4, 5) 
Size(Total elem in tensor ) :  tf.Tensor(120, shape=(), dtype=int32)
SIZE using.numpy()  :  120
Datatype of Every Element :  <dtype: 'float32'>
Element along the 0 axis : 2
Element along the Last axis : 5


### Indexing the tensors 
It can be done just like python list

In [ ]:
# Getting the first 2 elem of each dim
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Getting the first 1 elem of each dim except the last dim
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Getting the first 1 elem of each dim except the 2ndlast dim
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
random_tensor = tf.random.Generator.from_seed(10).uniform(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.93598676, 0.6513264 ],
       [0.31663585, 0.00111556],
       [0.9212191 , 0.3822806 ]], dtype=float32)>

In [ ]:
# Now get the last element of every row of above tensor 
random_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6513264 , 0.00111556, 0.3822806 ], dtype=float32)>

#### Adding an Extra dimension to tensor but keeping the data same
- tf.newaxis  : it is a parameter 
- tf.expand_dims(tensor,axis)  : it is a fucn

In [ ]:
# Adding extra dim to random_tensor
print(random_tensor.ndim,random_tensor.shape)
random_tensor[tf.newaxis]  # new axis created at 1st dim

2 (3, 2)


<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[0.93598676, 0.6513264 ],
        [0.31663585, 0.00111556],
        [0.9212191 , 0.3822806 ]]], dtype=float32)>

In [ ]:
# for it to create in 2nd dim 
random_tensor[:,tf.newaxis]  # new axis created at 2st dim


<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[0.93598676, 0.6513264 ]],

       [[0.31663585, 0.00111556]],

       [[0.9212191 , 0.3822806 ]]], dtype=float32)>

In [ ]:
# for it to create in 3rd dim 
# random_tensor[:,:,tf.newaxis]  # new axis created at 3rd dim

# or 
random_tensor[...,tf.newaxis]  # new axis created at 3rd dim


<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[0.93598676],
        [0.6513264 ]],

       [[0.31663585],
        [0.00111556]],

       [[0.9212191 ],
        [0.3822806 ]]], dtype=float32)>

In [ ]:
# Adding extra dim to random_tensor
# syntax : tf.expand_dims(tensor,axis)
print(random_tensor.ndim,random_tensor.shape)
tf.expand_dims(random_tensor,axis=-1)# new axis created at 3rd dim

2 (3, 2)


<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[0.93598676],
        [0.6513264 ]],

       [[0.31663585],
        [0.00111556]],

       [[0.9212191 ],
        [0.3822806 ]]], dtype=float32)>

In [ ]:
# Adding extra dim to random_tensor
# syntax : tf.expand_dims(tensor,axis)
print(random_tensor.ndim,random_tensor.shape)
tf.expand_dims(random_tensor,axis=0)# new axis created at 1 dim/oth axis

2 (3, 2)


<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[0.93598676, 0.6513264 ],
        [0.31663585, 0.00111556],
        [0.9212191 , 0.3822806 ]]], dtype=float32)>

### Manipulating the Tensors  (tensors operations)
Basic Operations 
- `+` , `-` , `*` ,`/`
- tf.multiply(tensor,10)
- tf.add(tensor,value) 
llly `tf.divide`

In [ ]:
tensor = tf.constant([[1,2],[10,20]])
tensor + 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  7],
       [15, 25]], dtype=int32)>

In [ ]:
# original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10, 20]], dtype=int32)>

In [ ]:
# similarly tensor-10 , tensor* 10 , tensor / 10  , tf.add(tensor,10) , tf.multiply(tensor,10) ,  tf.divide(tensor,10)

### Matrix Multiplication (common operation in deep learning )
> tf.matmul(mat1,mat2)<br>
> matrix1 @ matrix2
- There are two rules our tensors/matrices need to fulfil if we're going to matrix miltiply them :           
<h5>Rule 1</h5>  The inner dimensions must match
<h5>Rule 2</h5>  The resulting matrix has shape of Outer dimensions  
<h5>Example : </h5>
if two matrix with Shape  X=(3,2) and Y=(2,5)  then 2=2 => inner dimension 
and resultant matrix mul shape is x@Y shape =(3,5)

**📑Resource** : Regarding Matrix Multiplycation https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Matrix multi in tensor floww 
import tensorflow as tf
print(tensor);print()
tf.matmul(tensor,tensor)


tf.Tensor(
[[ 1  2]
 [10 20]], shape=(2, 2), dtype=int32)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 21,  42],
       [210, 420]], dtype=int32)>

In [ ]:
# above is the correct and using python "*" is wrong ans 
print(tensor,"\n\n X \n\n",tensor,"\n\n\n = ",tensor*tensor)

# This one is wrong ans 

tf.Tensor(
[[ 1  2]
 [10 20]], shape=(2, 2), dtype=int32) 

 X 

 tf.Tensor(
[[ 1  2]
 [10 20]], shape=(2, 2), dtype=int32) 


 =  tf.Tensor(
[[  1   4]
 [100 400]], shape=(2, 2), dtype=int32)


In [ ]:
# so to do it by pythonic way we have to use :   "@" this operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 21,  42],
       [210, 420]], dtype=int32)>

In [ ]:
# Creating a tensor (3,2) tensor 
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# THERE WILL BE DEFINATELY EROR HERE!!  becz inner dim doesn't match 
X @ Y

InvalidArgumentError: ignored

In [ ]:
# reshaping X and them multiplying them
# lets make X as 2,3 since inner remains same in both i.e 3 and ther 2*3 should remain 6
X =tf.reshape(X,shape=(2,3))
X@Y    #  2,3   X   3,2  =  2,2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
#Note above we converted shape of X from 2,3 to 3,2 
# we cando it by transpose also 
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]]) # 3,2
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]]) # 3,2
# tf.transpose(X) @ Y          # 2,3   X   3,2  =  2,2    OR
tf.matmul(tf.transpose(X),Y )  # 2,3   X   3,2  =  2,2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
import tensorflow as tf
import